### ISSUE TITLE
问一下 这个kafka-core是不是传错了

### ISSUE THREAD

**Issue by hhhizzz** [wanghan0501/WiFiProbeAnalysis#2]
还没仔细读代码，但是kafka-core里的readme是有关web的，还有pom.xml里也没有和kafka相关的依赖

**Comment by wanghan0501** [comment]
I will check it later

**Comment by wanghan0501** [comment]
the problem has been fixed, and right code has been pushed

**Comment by hhhizzz** [comment]
thanks
