### ISSUE TITLE
您好，是否能提供一个比较详细的部署文档的呀，参考readme了，部署起来还是有报错，没跑起来，多谢：）

### ISSUE THREAD

**Issue by yuxingfafu** [wanghan0501/WiFiProbeAnalysis#3]
您好，是否能提供一个比较详细的部署文档的呀，参考readme了，部署起来还是有报错，没跑起来，多谢：）

**Comment by Maicius** [comment]
这几天在建模，比较忙...之后会慢慢补充，主要是版本依赖容易出问题

**Comment by Maicius** [comment]
已更新文档和部分项目代码、依赖，如果还是出错的话，可以把问题截图附上
